# 📘 Introduction to NumPy

NumPy (Numerical Python) is a powerful Python library for numerical computing. It provides support for arrays, matrices, and many mathematical functions.

# 🧱 Array Creation

Arrays are the foundation of NumPy. You can create arrays from Python lists using `np.array()`. There are also functions like `np.zeros()`, `np.ones()`, `np.arange()`, and `np.linspace()`.

# 🧾 Array Attributes

Once an array is created, you can inspect its shape, size, number of dimensions, and data type using attributes like `.shape`, `.ndim`, `.size`, and `.dtype`.

# 🔍 Indexing and Slicing

You can access individual elements or slices (subsets) of a NumPy array using square brackets, similar to Python lists. NumPy also supports advanced slicing.

# ➕ Arithmetic Operations

NumPy arrays support element-wise arithmetic operations (like `+`, `-`, `*`, `/`, `**`). These are applied to each element of the array.

# 🎯 Broadcasting

Broadcasting allows NumPy to perform operations between arrays of different shapes in a memory-efficient way.

# 🔧 Useful Functions

NumPy includes many useful functions like `np.sum()`, `np.mean()`, `np.std()`, `np.max()`, `np.min()`, and more for performing statistical and mathematical operations.

# 🔁 Reshaping and Flattening

`reshape()` changes the shape of an array, and `flatten()` or `ravel()` turns a multi-dimensional array into a 1D array.

# 🧩 Stacking and Splitting Arrays

`hstack()`, `vstack()`, and `concatenate()` are used for joining arrays, while `hsplit()`, `vsplit()`, and `split()` are used for dividing arrays.

# 🎲 Random Module in NumPy

NumPy's `random` module lets you generate random numbers, including integers, floats, normal distributions, etc.

In [3]:
import numpy as np

# Array Creation 

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [51]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l
# It Vector or 1D Array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [52]:
np.array(l) 
# And it is Matrics or 2D Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Basic Array Generation

In [10]:
np.arange(1,9)
# Its like range fuction in loops

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.zeros(10)
# It is used to print zeros only and it is printed in vector form

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,10))
# It will print 5 rows and 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.linspace(1,20)
# This function provides the same or linear space between two or more eliments

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

# Random Generation Functions

In [20]:
np.random.rand(10)
# It will print random numbers from 0 to 1
# This is also called normalization in stats

array([0.59409249, 0.59608034, 0.64785113, 0.63424458, 0.97557874,
       0.67543381, 0.22034251, 0.32482184, 0.0730543 , 0.43728496])

In [30]:
np.random.randn(10)
# Now this will print random numbers between -3 to 3ab
# And it is also called as standardization

array([-0.31551853, -1.76826033, -0.12227819, -0.31039534,  1.45007589,
       -1.04023585, -0.72822842,  0.29946798,  0.08851753, -2.17612229])

In [32]:
np.random.randint(10,20,10)
# It will print random numbers from 10 to 20 and stores in an array

array([11, 11, 11, 19, 18, 16, 10, 14, 12, 12])

# Array Attributes

In [34]:
arr = np.array([[1,2,3,],[4,5,6,],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape

(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int32')

# Array Methodes

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.min()

1

In [40]:
arr.max()

9

In [41]:
arr.sum()

45

In [44]:
np.sum(arr,axis=1)
# Here 0 means vertical sum and 1 means horizontal sum

array([ 6, 15, 24])

In [45]:
arr.mean()

5.0

In [46]:
arr.std()

2.581988897471611

In [47]:
arr.argmax()

8

In [48]:
arr.argmin()

0

# Reshaping And Resizing

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [50]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# NumPy indexing and Slicing of vectors

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[1:6]

array([12, 13, 14, 15, 16])

# Numpy indexing and slicing of matrix

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[3,4]

20

In [21]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

# Boolean Indexing

In [22]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
bool_index = arr  %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [26]:
arr = arr[bool_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# NumPy Operations

# Arithematic Operations

In [30]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [31]:
a1

array([1, 2, 3, 4, 5])

In [32]:
a2

array([ 6,  7,  8,  9, 10])

In [33]:
a1 + a2

array([ 7,  9, 11, 13, 15])

# broadCasting

In [34]:
l = [20,30,40,50]
arr = np.array(l)

In [35]:
arr

array([20, 30, 40, 50])

In [36]:
arr+10

array([30, 40, 50, 60])

Deep And Shallow Copy

In [40]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [43]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
a[4:6] *10

array([50, 60])

In [46]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
b = a

In [48]:
b[0] = 99

In [49]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
A =np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [54]:
A

array([[1, 2],
       [3, 4]])

In [55]:
B

array([[5, 6],
       [7, 8]])

In [57]:
A * B

array([[ 5, 12],
       [21, 32]])

In [58]:
A @ B

array([[19, 22],
       [43, 50]])

In [59]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [60]:
A.T

array([[1, 3],
       [2, 4]])

# Array Manipulation

In [62]:
a = np.array([1,2,3,4,])
b = np.array([5,6,7,8])

In [64]:
a


array([1, 2, 3, 4])

In [65]:
b

array([5, 6, 7, 8])

In [66]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [69]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [77]:
a = np.vsplit(c,2)

In [78]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
