# NumPy

In [1]:
# first of all we need to import numpy.

In [2]:
import numpy as np

In [3]:
# creating np array.

In [4]:
arr = np.array([1,2,3,4,5]) # 1D array

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array([[1,2,3,4] ,[5,6,7,8]]) # 2D array

In [7]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
# converting list into array

In [9]:
list1 = [1,2,3,4,5,6,7,8,9]

In [10]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
type(list1)

list

In [12]:
arr1 = np.array(list1)

In [13]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(arr1)

numpy.ndarray

# Numpy.ndarray

In [15]:
# arange()

In [16]:
a = np.arange(5)

In [17]:
a

array([0, 1, 2, 3, 4])

In [18]:
a1 = np.arange(0,10) 

In [19]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a2 = np.arange(0,10,2) # start-end-step

In [21]:
a2 

array([0, 2, 4, 6, 8])

In [22]:
# zeros

In [23]:
b = np.zeros(10) #create a array of value zeros.But it is by default float.

In [24]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
b = np.zeros((5,5))

In [26]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
b = np.zeros((5,5))

In [28]:
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
b1 = np.zeros(10, dtype=int) # for integer.

In [30]:
b1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
b1 = np.zeros((10,10),dtype=int) # 10 x 10 matrix

In [32]:
b1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
 # ones

In [34]:
c = np.ones(10) # now element value is 1

In [35]:
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
c = np.ones((5,5)) # 5x5 matrix dtype float.

In [37]:
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
c1 = np.ones(10,dtype=int) # change data type

In [39]:
c1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [40]:
c1 = np.ones((10,10),dtype=int)

In [41]:
c1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [42]:
# random,rand,randint.

In [43]:
r = np.random.rand(5) # generating 5 diff random no. but in float

In [44]:
r

array([0.05166883, 0.29238661, 0.05192074, 0.62780078, 0.78165781])

In [45]:
r = np.random.rand(5,6) # 5 x 6 matrix

In [46]:
r

array([[0.49183565, 0.10226467, 0.16356302, 0.84294697, 0.92139015,
        0.84964984],
       [0.96257033, 0.54799343, 0.92834302, 0.16924088, 0.86031376,
        0.41781285],
       [0.6268112 , 0.12996468, 0.08785506, 0.76279169, 0.38526431,
        0.92747179],
       [0.36335713, 0.85401527, 0.37407753, 0.98080437, 0.51328638,
        0.58279104],
       [0.98483344, 0.8297037 , 0.42755384, 0.38891192, 0.38695061,
        0.65031986]])

In [47]:
# for int no.

In [48]:
rint = np.random.randint(5) # generating random no. but less than 5 .

In [ ]:
rint 