#Importing Liberaries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

#checking the virsion of tensorflow

In [4]:
tf.__version__

'2.20.0'

#Loading The Dataset

In [5]:
dataset = pd.read_csv(r"C:\Users\HP\Downloads\Churn_Modelling.csv")

#Splitting The Dataset

In [6]:
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [7]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [8]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

#Using LabelEncoder

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [12]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

#Using ColumnTransformer and OneHotEncoder

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [14]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

#Using StandardScaler

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [16]:
x

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

#Training and testing of features

In [17]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [19]:
print(x_train.shape)
print(x_test.shape)   
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


# ANN Model Building:-

In [20]:
ann = tf.keras.models.Sequential()

In [22]:
ann.add(tf.keras.layers.Dense(units=6))

In [23]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [25]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [26]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.7933 - loss: 0.5105
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8076 - loss: 0.4510
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8110 - loss: 0.4372
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8156 - loss: 0.4289
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8180 - loss: 0.4229
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8215 - loss: 0.4182
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8240 - loss: 0.4134
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.8253 - loss: 0.4087
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8255 - loss: 0.4049
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8270 - loss: 0.4012
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8284 - loss: 0.3973
Epoch 12/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7

In [27]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Artificial Neural Networks (ANN) in Machine Learning

## 1. Introduction
Artificial Neural Networks (ANNs) are computational models inspired by the structure and function of the human brain.  
They consist of layers of interconnected units called **neurons**, which are capable of learning complex patterns from data.  
Each neuron receives inputs, applies **weights** and a **bias**, and then passes the result through an **activation function** to produce an output.

---

## 2. Structure of an ANN

### Layers
- **Input Layer**: Accepts the input features from the dataset.  
- **Hidden Layers**: Perform computations and extract relationships between features.  
- **Output Layer**: Produces the final prediction (classification or regression).

### Neuron Computation
For a given neuron:
\[
z = (w_1 \cdot x_1 + w_2 \cdot x_2 + \ldots + w_n \cdot x_n) + b
\]
\[
a = Activation(z)
\]

Where:  
- \( w_i \) = weight  
- \( x_i \) = input feature  
- \( b \) = bias  
- \( a \) = neuron output after applying activation  

---

## 3. Working of an ANN

1. **Forward Propagation**  
   - Inputs are multiplied with weights, bias is added, and activation functions are applied.  
   - The output of one layer becomes the input to the next.  

2. **Loss Function**  
   - Measures the difference between predicted output and actual target.  
   - Examples:  
     - Classification → Binary Crossentropy, Categorical Crossentropy  
     - Regression → Mean Squared Error  

3. **Backpropagation**  
   - Error is propagated backward through the network.  
   - Gradients are calculated using calculus (chain rule).  
   - Weights are updated to minimize the loss.  

4. **Gradient Descent Optimization**  
   - Updates weights using:  
   \[
   w = w - \eta \cdot \frac{\partial L}{\partial w}
   \]  
   where \( \eta \) = learning rate, \( L \) = loss.  

5. **Epochs**  
   - One complete pass of the training dataset through the ANN.  
   - Training continues for multiple epochs until the model converges.  

---

## 4. Activation Functions

Activation functions introduce **non-linearity**, enabling the network to learn complex patterns.

- **Sigmoid**:  
  \[
  f(x) = \frac{1}{1 + e^{-x}}
  \]  
  Range: (0,1) → Often used for probabilities.  

- **Tanh**:  
  Range: (-1,1) → Centered at zero, useful for balanced outputs.  

- **ReLU (Rectified Linear Unit)**:  
  \[
  f(x) = \max(0, x)
  \]  
  Most widely used in hidden layers.  

- **Softmax**:  
  Converts outputs into probabilities for multi-class classification.  


